package br.univates.java.poo.pratica25;

import lombok.Getter;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 * @author jean.franz
 * @date 08/06/2021
 **/
@Getter
public class ListaContatos extends JFrame {
    private JPanel panel;
    private JButton addContatoButton;
    private JTable listContatos;
    private JButton editContatoButton;
    private JButton deleteContatoButton;
    private DefaultTableModel model;

    public ListaContatos() {

        setLocationRelativeTo(null);

        model = (DefaultTableModel) listContatos.getModel();

        criarTabela();

        addContatoButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                ViewContato vc = new ViewContato();
                vc.setContentPane(vc.getPanel());
                vc.setTitle("Adicionar contato");
                vc.pack();
                vc.setVisible(true);
                vc.addContato(ListaContatos.this);
            }
        });

        editContatoButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                ViewContato vc = new ViewContato();
                vc.setContentPane(vc.getPanel());
                vc.setTitle("Editar contato");
                vc.pack();
                vc.setVisible(true);
                vc.editContato(ListaContatos.this);
            }
        });

        deleteContatoButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                DeleteContato dc = new DeleteContato();
                dc.setContentPane(dc.getPanel());
                dc.setTitle("Excluir contato");
                dc.pack();
                dc.setVisible(true);
                dc.deleteContato(ListaContatos.this);
            }
        });
    }

    public void criarTabela() {
        model.addColumn("ID");
        model.addColumn("Nome");
        model.addColumn("Telefone");
        model.addColumn("Email");

        loadContatos();

        listContatos.getColumnModel().getColumn(0).setPreferredWidth(2);
    }

    public void loadContatos() {

        model.setRowCount(0);

        ContatoDAO dao = new ContatoDAO();
        ArrayList<Contato> contatos = dao.ler();

        Object[] dadosTabela = new Object[4];

        for (int i = 0; i < contatos.size(); i++) {
            dadosTabela[0] = (i + 1);
            dadosTabela[1] = contatos.get(i).getNome();
            dadosTabela[2] = contatos.get(i).getTelefone();
            dadosTabela[3] = contatos.get(i).getEmail();
            model.addRow(dadosTabela);
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(5, 5, 5, 5), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 4, new Insets(0, 0, 0, 0), -1, -1));
        panel.add(panel1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        panel1.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        editContatoButton = new JButton();
        editContatoButton.setText("Editar Contato");
        panel1.add(editContatoButton, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        addContatoButton = new JButton();
        addContatoButton.setText("Adicionar Contato");
        panel1.add(addContatoButton, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        deleteContatoButton = new JButton();
        deleteContatoButton.setText("Excluir Contato");
        panel1.add(deleteContatoButton, new com.intellij.uiDesigner.core.GridConstraints(0, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        panel.add(scrollPane1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        listContatos = new JTable();
        listContatos.setFillsViewportHeight(true);
        listContatos.setPreferredScrollableViewportSize(new Dimension(500, 100));
        scrollPane1.setViewportView(listContatos);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}